### ISSUE TITLE
Other Languages Support 

### ISSUE THREAD

**Issue by Bassil-GG** [appujet/lavamusic#409]
### Description of your suggestion

 You can use crowdin for the community to help with the translation progress

**Comment by brblacky** [comment]
crowdin ?

**Comment by Guazy** [comment]
> crowdin ?

https://crowdin.com/

https://www.transifex.com/

They allow free translations up to a certain number of characters. In short, you can benefit from these services free of charge for such project files.

Please let me know when you add multi-language support. I can translate it into "Turkish, French and Azerbaijani" languages for you. Thanks.
