### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by idMJA** [appujet/lavamusic#498]
so I'm trying to play music, but I can't because there's no sound coming out

**Comment by brblacky** [comment]
What is your lavalink version ?

**Comment by idMJA** [comment]
4.0.0

**Comment by bimaindrawans** [comment]
i faced the same problem, but in the console didn't show anything

**Comment by idMJA** [comment]
> Send me console log ss
@brblacky 
![IMG_2104](https://github.com/brblacky/lavamusic/assets/108927987/1fb26bed-09e8-41d4-9a74-2081658e0238)

**Comment by bimaindrawans** [comment]
![image](https://github.com/brblacky/lavamusic/assets/147312348/fd968a23-eb1c-4993-96a2-f76039df47df)

on replit, the keep_alive not working too, when i visit the link 
it's says
Hmm... We couldn't reach this Repl
Make sure this Repl has a port open and is ready to receive HTTP traffic.

**Comment by bimaindrawans** [comment]
![image](https://github.com/brblacky/lavamusic/assets/147312348/f797c0b0-897c-4c0a-85e4-c6221c7f63cf)

when i try to play a song, no sound coming out from the bot & no error log that i can provide

**Comment by brblacky** [comment]
Are you all using public lavalink server?

**Comment by idMJA** [comment]
> Are you all using public lavalink server?

nah, i use my own lavalink and i install lavasrc and lavasearch plugin that developed by topi314

**Comment by idMJA** [comment]
@brblacky resolve this please

**Comment by Xoloth** [comment]
not fixed. still no sound coming from the bot and there is no error log

**Comment by brblacky** [comment]
It is issue with your lavalink see your lavalink console

**Comment by Xoloth** [comment]
Lavalink also does not give me any error. I can post it here if you want.

**Comment by brblacky** [comment]
Send me here

**Comment by Xoloth** [comment]
![Ekran Resmi 2024-02-07 17 33 00](https://github.com/brblacky/lavamusic/assets/34619283/b7ae0684-44c0-48d0-a077-b8dfc42151e5)
![Ekran Resmi 2024-02-07 17 32 48](https://github.com/brblacky/lavamusic/assets/34619283/db008972-475c-44a4-81c9-4b454eb7a2c8)
Here, both Lavalink and Lavamusic and discord.

**Comment by Xoloth** [comment]
@brblacky Any update?

**Comment by LucasB25** [comment]
Your worry and you fix?

**Comment by Xoloth** [comment]
What?

**Comment by 0yz** [comment]
The only time i had the issue where there were no errors from Lavalink or the bot but also no sound from the bot while everything seemed to work was when the bot was not able to connect to the Discord voice chat ports due to the firewall.
