### ISSUE TITLE
[Feature Request] Insert a song into the current queue

### ISSUE THREAD

**Issue by Cold-EA** [appujet/lavamusic#509]
Hello,

I would like a feature where I can "Insert" a song into the current queue. 
Where I can add a song as the NEXT SONG to play in the queue, without disrupting or clearing the current queue.

Example: 
Normal queue: Song 1, Song 2, Song 3, Song 4
... after using the insert command to add a song: Song 5, Song 1, Song 2, Song 3, Song 4

Thanks In Advanced

**Comment by zebz213** [comment]
If you want to test the code, I have reworked the play command and made it work like you are requesting but as a new command /playnext. If you want to test it, you can copy the one added file over to yours for testing. But so far it seems to work as intended for me.  [https://github.com/zebz213/lavamusic/tree/PlayNext-Command](url)
