### ISSUE TITLE
247 resets on VC leave

### ISSUE THREAD

**Issue by funforgiven** [appujet/lavamusic#515]
We should be able to set a default value for 247. I don't want it to stay in VC after I leave. 7/24 works correctly if I disable it, but it is enabled again after disconnecting, so it does not leave automatically in next session.

**Comment by peyton2465** [comment]
Comment this line
https://github.com/appujet/lavamusic/blob/2b697a2b86db23c6f2dbb2dba411af965aa8512d/src/database/server.ts#L107

The guild id is inserted into the database if it does not exist. This is obviously not correct behavior. I'll make a PR.
