### ISSUE TITLE
Confusion with licenses

### ISSUE THREAD

**Issue by hikeri** [appujet/lavamusic#523]
Good afternoon. The description of your project says that it is licensed under the Apache-2.0 license. But the license text in the repository is GPL-3. Therefore, this code is licensed under GPL-3. But if it is licensed under GPL-3, then parts of the code "Copyright (c) 2023. All rights reserved." are violators of the GPL-3 license and are not compatible with it (since free modification must necessarily be allowed). [GPL Quick Guide](https://www.gnu.org/licenses/quick-guide-gplv3.en.html). Changing the license for Apache-2.0 is impossible without the consent of all contributors participating in the project after this change. 

Actually, the question arises whether copyright all rights reserved is valid in parts of the project code at all? 

[Example of copyrighted code in this repo](https://github.com/brblacky/lavamusic/blob/main/src/commands/info/About.ts)

**Comment by appujet** [comment]
you can modified code 

but you can't use for public bot
