### ISSUE TITLE
Video returned by YouTube isn't what was requested

### ISSUE THREAD

**Issue by xDroflLOL** [appujet/lavamusic#530]
https://github.com/lavalink-devs/Lavalink/issues/1030

**Comment by ramsy314** [comment]
This is a problem with Lavalink and not a bug for the code. We ask you to contact the developers of Lavalink. Thank you!

**Comment by xDroflLOL** [comment]
https://github.com/lavalink-devs/lavaplayer/pull/86 Looks like there's a lavaplayer PR that _should_ fix it.
