### ISSUE TITLE
Shuffling does not work properly; The shuffle command doesn't shuffle the first song in the queue

### ISSUE THREAD

**Issue by xDroflLOL** [appujet/lavamusic#535]
Load up songs (the more songs you load in the more obvious the problem, e.g. 5 might not be enough, but 500 will be more than enough), see queue, shuffle the queue, and see the queue again.

**Comment by pheeef** [comment]
I'm guessing this is intended behaviour since you wouldn't want to shuffle a song that is currently loaded in the player. 

You can see the implementation of the `setShuffle` Function in the `Dispatcher.ts` file (starts at Line 136).
```ts
 public setShuffle(shuffle: boolean): void {
        if (!this.player) return;
        this.shuffle = shuffle;
        if (shuffle) {
            const current = this.queue.shift();
            this.queue = this.queue.sort(() => Math.random() - 0.5);
            this.queue.unshift(current);
        } else {
            const current = this.queue.shift();
            this.queue = this.queue.sort((a: any, b: any) => a - b);
            this.queue.unshift(current);
        }
    }
```

As you can see in line 140 the first element is removed from the list with the `shift()` function.

**Comment by xDroflLOL** [comment]
What I mean is this: 
![image](https://github.com/appujet/lavamusic/assets/87008513/9d6bcdc7-aefb-4ac0-8f91-f28eb285a41a)
This is before shuffling.
![image](https://github.com/appujet/lavamusic/assets/87008513/36709a1c-2d4a-467f-8e17-11bef71621da)
This is after shuffling.
The first song _in the queue_ won't get shuffled, the rest do.

**Comment by Xenofic** [comment]
@xDroflLOL the first song is the current track, and hence it's not suffled

**Comment by xDroflLOL** [comment]
> @xDroflLOL the first song is the current track, and hence it's not suffled

![image](https://github.com/appujet/lavamusic/assets/87008513/b2b520ba-e62a-457b-bbc0-55ebbe2ac7cb)
![image](https://github.com/appujet/lavamusic/assets/87008513/d8fd7c52-7687-4381-9343-6ab3b1386b83)
![image](https://github.com/appujet/lavamusic/assets/87008513/37d2fb1f-c83c-431a-bccc-19ebeb5cdb78)
The first track in the queue isn't the track that's currently playing, it's a different track that is currently playing

**Comment by appujet** [comment]
Fixed  https://github.com/appujet/lavamusic/commit/378c330e1a61d60ba3f60915a3ea424eb3a8e93c
