### ISSUE TITLE
How to add lavamusic song activity status on wavemusic 

### ISSUE THREAD

**Issue by STARCAPIE** [appujet/lavamusic#569]

**Comment by LucasB25** [comment]
if you don’t describe with examples I close posts

**Comment by STARCAPIE** [comment]
> if you don’t describe with examples I close posts

![1242805518918090834remix-1716919094113](https://github.com/appujet/lavamusic/assets/147209934/ec9af76e-4b98-4c2f-974a-d7fdda5f8332)

**Comment by LucasB25** [comment]
anyway your steps on the right repo
