### ISSUE TITLE
Error while connecting with MongoDB through prisma 

### ISSUE THREAD

**Issue by hridayarajbanshi** [appujet/lavamusic#574]
Error: 
Invalid `prisma.product.create()` invocation:

Raw query failed. Code: `unknown`. Message: `Kind: Command failed: Error code 8000 (AtlasError): empty database name not allowed
	at 27104a8afcf9feb14d9195eba6a71827/atlasproxy/session_proxy.go:741
	at 27104a8afcf9feb14d9195eba6a71827/atlasproxy/session_proxy.go:1656
	at 27104a8afcf9feb14d9195eba6a71827/atlasproxy/session_proxy.go:1228
	at 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/proxy_session.go:369
	at 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/proxy_session.go:118
	at 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/session.go:220
	at 10gen/mongonet@v0.0.0-20240410162250-34650b689c2f/server.go:384
	at src/runtime/asm_arm64.s:1197, labels: {}`

**Comment by LucasB25** [comment]
It works just updates your code
