### ISSUE TITLE
Doesnt play anything and getting some errors on commands

### ISSUE THREAD

**Issue by Yerli-Oyuncu** [appujet/lavamusic#657]
Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs

**Comment by infnibor** [comment]
> Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs

What language are you using, do you have the latest code?

**Comment by Yerli-Oyuncu** [comment]
> > Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs
> 
> What language are you using, do you have the latest code?

Yes im using the latest code.

**Comment by infnibor** [comment]
> > > Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs
> > 
> > 
> > What language are you using, do you have the latest code?
> 
> Yes im using the latest code.

What language you using?

**Comment by Yerli-Oyuncu** [comment]
> > > > Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs
> > > 
> > > 
> > > What language are you using, do you have the latest code?
> > 
> > 
> > Yes im using the latest code.
> 
> What language you using?

Sorry, idk much on coding i just cloned on windows and followed the installation guide.

**Comment by infnibor** [comment]
> > > > > Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs
> > > > 
> > > > 
> > > > What language are you using, do you have the latest code?
> > > 
> > > 
> > > Yes im using the latest code.
> > 
> > 
> > What language you using?
> 
> Sorry, idk much on coding i just cloned on windows and followed the installation guide.

99.9% it's your lavalink server error, because this error is related to not reading the description of the variable assigned to it, provide the version number in package.json and when you downloaded the code, because it has been changing in recent days, and of course the logs/spring.log file, in the case of your own private lavalink server, and if you use a public server, use another one

**Comment by Yerli-Oyuncu** [comment]
> > > > > > Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs.
> > > > > 
> > > > > 
> > > > > What language are you using, do you have the latest code?
> > > > 
> > > > 
> > > > Yes im using the latest code.
> > > 
> > > 
> > > What language you using?
> > 
> > 
> > Sorry, idk much on coding i just cloned on windows and followed the installation guide.
> 
> 99.9% it's your lavalink server error, because this error is related to not reading the description of the variable assigned to it, provide the version number in package.json and when you downloaded the code, because it has been changing in recent days, and of course the logs/spring.log file, in the case of your own private lavalink server, and if you use a public server, use another one.As for the bad display error, I think I found the culprit, when I come back from my trip I will test it and let you know what and how

Thanks, i tried another public server and its worked, i also tried other versions of lavalink and mine doesnt work

**Comment by X-olli** [comment]
Hello @Yerli-Oyuncu , can you give me the latest version of the code because I have a problem with it please.

**Comment by infnibor** [comment]
> Hello @Yerli-Oyuncu , can you give me the latest version of the code because I have a problem with it please.

In the latest code ist latest download od branch main

**Comment by Yerli-Oyuncu** [comment]
> > Hello @Yerli-Oyuncu , can you give me the latest version of the code because I have a problem with it please.
> 
> In the latest code ist latest download od branch main
> 
> https://github.com/appujet/lavamusic/releases/tag/v4.6.7
> 
> Although it is best to download from the main branch because there were some changes in the translation files after this release

Thanks for your help, i found my problem. Someone said i have to use ipv6 for lavalink and my provider doesnt give. Ill buy another server for it.

**Comment by infnibor** [comment]
> Bot joins the channel but doesnt play anything also when i try to clear queue it gives cmd.player.errors.no_songs

Fixed in PR https://github.com/appujet/lavamusic/pull/670
