### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'locale')

### ISSUE THREAD

**Issue by EastWestGamer** [appujet/lavamusic#663]
Hello,

When I try to play anything or use command there is an error in lavamusic log.
No error in lavalink.

![image](https://github.com/user-attachments/assets/6717e0ac-0723-47a3-98be-78b5c898a6a9)

Lavamusic version: latest
Lavalink version: latest

**Comment by Vretu-Dev** [comment]
> Hello,
> 
> When I try to play anything or use command there is an error in lavamusic log. No error in lavalink.
> 
> ![image](https://private-user-images.githubusercontent.com/100802403/355053710-6717e0ac-0723-47a3-98be-78b5c898a6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTgyMTQsIm5iZiI6MTcyMjg1NzkxNCwicGF0aCI6Ii8xMDA4MDI0MDMvMzU1MDUzNzEwLTY3MTdlMGFjLTA3MjMtNDdhMy05OGJlLTc4YjVjODk4YTZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxMTM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OTUzY2Y4NDdhNjNhMDEwN2EwNWZkNjI2ZjA0MjAwNTJiZmY4ODM1ZDJhNzJiZTA2NGI2NDVhNWFiNWVjOThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lnhme-ZF63uKNtFf3PigmCIcnN3o0jifEUL65lJV3Aw)
> 
> Lavamusic version: latest Lavalink version: latest

same issue

**Comment by whlack** [comment]
> Hello,
> 
> When I try to play anything or use command there is an error in lavamusic log. No error in lavalink.
> 
> ![image](https://private-user-images.githubusercontent.com/100802403/355053710-6717e0ac-0723-47a3-98be-78b5c898a6a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODgwMDQsIm5iZiI6MTcyMjg4NzcwNCwicGF0aCI6Ii8xMDA4MDI0MDMvMzU1MDUzNzEwLTY3MTdlMGFjLTA3MjMtNDdhMy05OGJlLTc4YjVjODk4YTZhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxOTU1MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDgyYWRlNDljNGQyZDMxZTMzNDI2MjUzZmU4NTQyZTY5Mjc2Yjk2MGY0NWRmMjg2NThjNWU0OWJhNmQ4NjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EOgrAurXEGp-YwEKs7Jjs0neL4tDHI9OB4G0VLlQ44E)
> 
> Lavamusic version: latest Lavalink version: latest

Same error

**Comment by whlack** [comment]
Fixed in PR #665 
Workaround: add to .env:
DEFAULT_LANGUAGE="EnglishUS"
