### ISSUE TITLE
Locale, lavalink 

### ISSUE THREAD

**Issue by Vretu-Dev** [appujet/lavamusic#664]
![image](https://github.com/user-attachments/assets/5572d96d-4af2-4664-b452-da2e410d7ddd)

**Comment by Vretu-Dev** [comment]
Why create 2 network
![image](https://github.com/user-attachments/assets/f2bfb387-9e0b-4654-bdcd-46fb4228e507)

**Comment by Vretu-Dev** [comment]
and why I can't mount locales directory
![image](https://github.com/user-attachments/assets/5ecf8dc6-0c06-43c7-b4d4-f2c77881524b)
![image](https://github.com/user-attachments/assets/e52e10b8-d1e6-402c-b346-f0b36eba4b0d)

**Comment by Vretu-Dev** [comment]
> Why create 2 network ![image](https://private-user-images.githubusercontent.com/82831707/355074641-f2bfb387-9e0b-4654-bdcd-46fb4228e507.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTgwMzYsIm5iZiI6MTcyMjg1NzczNiwicGF0aCI6Ii84MjgzMTcwNy8zNTUwNzQ2NDEtZjJiZmIzODctOWUwYi00NjU0LWJkY2QtNDZmYjQyMjhlNTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMzUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMWU5YjdhNTAwMTE4MzBiM2JmNjJlZjg3MmY5YTI4MGZiYWJjOGNjNjk3MzIzYmYzZWVmNjRjNThmYWFmOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nRqTFjeEqLB6j_yPQoE1K6CofNMGxlOwtVkHOrp6tjg)

I think it's require to add lavamusic to same network as lavalink
networks:
            - lavalink

**Comment by Vretu-Dev** [comment]
Like that
services:
    ## services for lavalink
    lavalink:
        container_name: lavamusic-lavalink
        image: ghcr.io/lavalink-devs/lavalink
        restart: on-failure
        environment:
            - SERVER_PORT=2333
        volumes:
            # mount application.yml from the same directory or use environment variables
            - ./Lavalink/application.yml:/opt/Lavalink/application.yml
            # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
            - ./Lavalink/plugins/:/opt/Lavalink/plugins/
        
        networks:
            - lavalink
        #expose:
        # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
        #- 2333
        #ports:
        # you only need this if you want to make your lavalink accessible from outside of containers
        #- "2333:2333"
        healthcheck:
            test: 'curl -H "Authorization: youshallnotpass" -s http://localhost:2333/version'
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 10s
    # services for postgresql database
    # postgres:
    #         container_name: lavamusic-postgres
    #         image: postgres:16
    #         restart: on-failure
    #         environment:
    #             POSTGRES_USER: lavamusic
    #             POSTGRES_PASSWORD: lavamusic
    #             POSTGRES_DB: lavamusic
    #
    #         volumes:
    #             - ./Postgres/data:/var/lib/postgresql/data
    #         healthcheck:
    #             test: 'pg_isready -U lavamusic'
    #             interval: 10s
    #             timeout: 10s
    #             retries: 5
    #             start_period: 10s

    # services for mongodb database
    #mongodb:
    #container_name: lavamusic-mongodb
    #image: 'bitnami/mongodb:4.4'
    #restart: on-failure
    #environment:
    #MONGODB_ADVERTISED_HOSTNAME: 127.0.0.1
    #MONGODB_REPLICA_SET_MODE: primary
    #MONGODB_ROOT_USER: mongoadmin
    #MONGODB_ROOT_PASSWORD: mongopassword
    #MONGODB_REPLICA_SET_KEY: replicasetkey123
    #volumes: - ./MongoDB/data:/data/db

    # services for lavamusic
    lavamusic:
        container_name: lavamusic
        image: ghcr.io/appujet/lavamusic:main
        environment:
            # Your lavalink url
            - LAVALINK_URL=lavalink:2333
            # Your lavalink password
            - LAVALINK_AUTH=youshallnotpass
            # Your lavalink name
            - LAVALINK_NAME=LavaMusic
            # Your lavalink secure (true or false)
            - LAVALINK_SECURE=false
            # database url
        #    - DATABASE_URL= put your database url here (mongodb or postgres)
        #   - DATABASE_URL=postgresql://lavamusic:lavamusic@postgres:5432/lavamusic (for postgres)
        #   - DATABASE_URL=mongodb://mongoadmin:mongopassword@mongodb:27017/lavamusic?authSource=admin (for mongodb)

        volumes:
            # mount .env from the same directory or use environment variables
            - .env:/opt/lavamusic/.env
            - ./locales:/opt/lavamusic/locales
        restart: on-failure
        depends_on:
            lavalink:
                condition: service_healthy

        networks:
            - lavalink
networks:
    lavalink:
        name: lavalink

**Comment by infnibor** [comment]
> ![image](https://private-user-images.githubusercontent.com/82831707/355073459-5572d96d-4af2-4664-b452-da2e410d7ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTgyNzYsIm5iZiI6MTcyMjg1Nzk3NiwicGF0aCI6Ii84MjgzMTcwNy8zNTUwNzM0NTktNTU3MmQ5NmQtNGFmMi00NjY0LWI0NTItZGEyZTQxMGQ3ZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMzkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiODlmMDcxYzAwNjE0YWMzMzNiMTAwY2NjNTcyNTIyOTg3NjExMjQ5OGIzODEyMjFiZDE0Yzk0NWU0OWFjN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AJWrr83DXjaGmb3KcjrSH1ruIjWm6ypBa3o3m3uWTO4)

Issue is your lavalink, problem with conecting with lavalink server.

**Comment by F9Alejandro** [comment]
Above fixed the issue for me. Not having that network means that lavamusic is unable to see lavalink service.

**Comment by Diyagi** [comment]
I would suggest removing that network from compose.
Unless theres an reason that i cant see for that network to exist, compose already creates an default network for the stack that should be enough.
If you want to just rename that network that can be done with
```yml
networks:
    default:
        name: lavalink
```
instead.

**Comment by Vretu-Dev** [comment]
> I would suggest removing that network from compose. Unless theres an reason that i cant see for that network to exist, compose already creates an default network for the stack that should be enough. If you want to just rename that network that can be done with
> 
> ```yaml
> networks:
>     default:
>         name: lavalink
> ```
> 
> instead.

yea this solved this problem
