### ISSUE TITLE
A bug that prevents players from being deleted when exported from a bot voice channel needs to be patched.

### ISSUE THREAD

**Issue by CuteStars** [appujet/lavamusic#715]
The title and content are the same, but if you export the bot from the voice channel after playing music, the player is not deleted properly, so if you want to play it again, you must use the /leave command to delete the player and then play it.

**Comment by CuteStars** [comment]
> Video please

discord dm check please

**Comment by LucasB25** [comment]
Envoie la ici et en format mp4

**Comment by CuteStars** [comment]
> 여기로 mp4 형식으로 보내주세요


Uploading 2024-09-02-21-12-10.mp4…

**Comment by CuteStars** [comment]
> 여기로 mp4 형식으로 보내주세요


https://github.com/user-attachments/assets/ff67980e-7f7c-48e3-9391-058e9bf3461d

**Comment by LucasB25** [comment]
247 active ?

**Comment by CuteStars** [comment]
> 247 active ?

no

**Comment by LucasB25** [comment]
Create PR

**Comment by CuteStars** [comment]
@Parthsonare I tried applying this code, but when I quit and played again, the button panel was displayed properly, but the bot entered the voice channel and did not play the song.

**Comment by LucasB25** [comment]
> # J’ai travaillé dessus et voici la solution :
> ### **VoiceStateUpdate.ts**
> ```
> import {
>   ChannelType,
>   type GuildMember,
>   type VoiceState,
>   EmbedBuilder,
>   Collection,
> } from "discord.js";
> import { Event, type Lavamusic} from "../../structures/index.js";
> 
> export default class VoiceStateUpdate extends Event {
>   constructor(client: Lavamusic, file: string) {
>     super(client, file, {
>       name: "voiceStateUpdate",
>     });
>   }
> 
>   public async run(oldState: VoiceState, newState: VoiceState): Promise<void> {
>     const guildId = newState.guild.id;
>     if (!guildId) return;
> 
>     const player = this.client.queue.get(guildId);
>     if (!player) return;
> 
>     const vcConnection = player.node.manager.connections.get(guildId);
>     if (!vcConnection?.channelId) return;
> 
>     const vc = newState.guild.channels.cache.get(vcConnection.channelId);
>     if (!vc || !this.isValidVoiceChannel(vc)) {
>       player.destroy();
>       return;
>     }
> 
>     const is247 = await this.client.db.get_247(guildId);
> 
>     if (!newState.guild.members.me?.voice.channelId && !is247 && player) {
>       player.destroy();
>       return;
>     }
> 
>     if (
>       newState.id === this.client.user.id &&
>       newState.channelId &&
>       newState.channel?.type === ChannelType.GuildStageVoice &&
>       newState.guild.members.me?.voice.suppress
>     ) {
>       if (
>         newState.guild.members.me?.permissions.has(["Connect", "Speak"]) ||
>         newState.channel
>           .permissionsFor(newState.guild.members.me)
>           ?.has("MuteMembers")
>       ) {
>         await newState.guild.members.me?.voice.setSuppressed(false).catch(() => {});
>       }
>     }
> 
>     if (newState.id === this.client.user.id) {
>       if (!newState.channelId) {
>         player.destroy();
>       } else if (
>         !newState.serverDeaf &&
>         vc.permissionsFor(newState.guild.members.me)?.has("DeafenMembers")
>       ) {
>         await newState.setDeaf(true);
>       }
> 
>       if (newState.serverMute && !player.paused) {
>         player.pause();
>       } else if (!newState.serverMute && player.paused) {
>         player.pause();
>       }
>       return;
>     }
> 
>     const vcMembers = this.getVoiceChannelMembers(vc);
> 
>     if (vcMembers.length <= 0) {
>       setTimeout(async () => {
>         const updatedVcConnection = player.node.manager.connections.get(guildId);
>         if (!updatedVcConnection?.channelId) {
>           player.destroy();
>           return;
>         }
> 
>         const playerVoiceChannel = newState.guild.channels.cache.get(
>           updatedVcConnection.channelId
>         );
>         if (
>           player &&
>           playerVoiceChannel &&
>           this.isValidVoiceChannel(playerVoiceChannel) &&
>           this.getVoiceChannelMembers(playerVoiceChannel).length <= 0
>         ) {
>           if (!is247) {
>             const embed = new EmbedBuilder()
>               .setColor("#ff0000")
>               .setTitle("I was alone in the voice channel, so I left.")
>               .setDescription(
>                 "If you want me to stay in the voice channel, please use the `247` command."
>               )
>               .setTimestamp();
> 
>             const channel = newState.guild.channels.cache.find(
>               (ch) => ch.type === ChannelType.GuildText
>             );
>             if (channel?.isTextBased()) {
>               await channel.send({ embeds: [embed] });
>             }
> 
>             player.destroy();
>           }
>         }
>       }, 5000);
>     }
> 
>     if (oldState.channelId && !newState.channelId) {
>       const oldChannel = oldState.guild.channels.cache.get(oldState.channelId);
>       if (oldChannel && this.isValidVoiceChannel(oldChannel)) {
>         const oldChannelMembers = this.getVoiceChannelMembers(oldChannel);
>         if (oldChannelMembers.length === 1 && oldChannelMembers[0].id === this.client.user.id) {
>           player.destroy();
>         }
>       }
>     }
>   }
> 
>   private isValidVoiceChannel(channel: any): channel is { members: Collection<string, GuildMember> } {
>     return channel && channel.members instanceof Collection;
>   }
> 
>   private getVoiceChannelMembers(channel: { members: Collection<string, GuildMember> }): GuildMember[] {
>     return [...channel.members.values()].filter((x: GuildMember) => !x.user.bot);
>   }
> }
> ```
> 
> ### Et la commande en jeu ajoutée (si le bot est connecté à null VC disconnect) :
> ```
>   if (!player.channelId) {
>                 await player.destroy();
>                 return await ctx.sendMessage({
>                     content: "",
>                     embeds: [
>                         this.client.embed()
>                             .setColor(this.client.color.red)
>                             .setDescription("The bot is not connected to a valid voice channel. Disconnected.")
>                     ],
>                 });
>             }
> ```
> 
> Vous pouvez copier cette logique, il y a aussi un changement dans l’embed
> 
> Bug corrigé | Ceci est mon code de dépôt personnalisé ! si vous rencontrez un problème, demandez à GPT

Please avoid using 100% what ChatGPT does because the code you provided is completely illogical on some points and it has a lot of totally idiotic and bugged changes

**Comment by LucasB25** [comment]
There is nothing to put in play, it’s not where you have to manage, null...

**Comment by CuteStars** [comment]
I changed the code in the newly updated VoiceStateUpdate.ts file from the old code to the new code, and the same thing still happens. This phenomenon occurs when you are kicked out of a voice chat room rather than a server mute.

**Comment by Vretu-Dev** [comment]
@appujet Can you fix this same issue

**Comment by LucasB25** [comment]
Issues will be fixed in main branch within some time
