### ISSUE TITLE
Bot not work on ARM Aarch64

### ISSUE THREAD

**Issue by Vretu-Dev** [appujet/lavamusic#725]
https://github.com/user-attachments/assets/23132885-219b-4540-ae81-b0ee2b02e940

**Comment by Vretu-Dev** [comment]
I have already hosted on Normal x86 and it works

**Comment by LucasB25** [comment]
what branch ?

**Comment by Vretu-Dev** [comment]
Two on main

**Comment by Vretu-Dev** [comment]
This is a bot running normally on x86 and does not have this problem
https://github.com/user-attachments/assets/cec79eb1-f53e-467e-8776-da7ee709d067

**Comment by LucasB25** [comment]
It works under ARM without problem, your machine has problems
