### ISSUE TITLE
[Bug]: Song request channel message don't update after the end of a song

### ISSUE THREAD

**Issue by ShirowLeBG** [appujet/lavamusic#732]
### Bug description

When playing a song via the bot, the title and cover image correctly appear in the Song Request channel. However, once the track finishes, the message does not reset. It continues to display the previous track's information (title and cover) as if the song is still playing. This issue persists even after using the /leave command. The only way to clear the message is to manually stop another currently playing song, at which point the message updates correctly. Otherwise, the message remains stuck as if a song is still active.

### Steps to reproduce

1. Play a song.
2. Wait for the song to finish.
3. The bot's message in the Song Request channel will not reset.

### Operating System

Ubuntu 22.04.5

### Node.js version

20.11.0

### java version

17

### Application/Library version

lastest

### Error logs or screenshots

![image](https://github.com/user-attachments/assets/6a4fa651-cdb9-41e3-b87b-b88d7b3d0793)
Here the song is over and the bot leaved the channel

**Comment by SsSAtonioSsS** [comment]
Also this message is not updated when a track is skipped. Only a signature is added, who skipped to the old track.
![image](https://github.com/user-attachments/assets/6773e4db-6e27-4c41-9c06-21163e98778b)
![image](https://github.com/user-attachments/assets/ce323005-d630-4450-a295-ab916d340776)

**Comment by hwangsihu** [comment]
Thanks, but it's not completely fixed yet. When I stop the song with the command, it still doesn't update.

**Comment by LucasB25** [comment]
> Thanks, but it's not completely fixed yet. When I stop the song with the command, it still doesn't update.

I tested it works

**Comment by hwangsihu** [comment]
Try Leave command.

**Comment by hwangsihu** [comment]
Stop is working but leave don't update

**Comment by hwangsihu** [comment]
Good

**Comment by hwangsihu** [comment]
It doesn't seem to update even when I skip a song or play the previous song.

**Comment by ShirowLeBG** [comment]
> It doesn't seem to update even when I skip a song or play the previous song.

Yeah same for me

**Comment by ShirowLeBG** [comment]
No news about this ? Still not working
