### ISSUE TITLE
[Bug]: Error on startup

### ISSUE THREAD

**Issue by SsSAtonioSsS** [appujet/lavamusic#733]
### Bug description

An error occurs when running the bot.

### Steps to reproduce

Install the bot in steps:
https://github.com/appujet/lavamusic/blob/main/README.md

### Operating System

Ubuntu 22.04.5 LTS

### Node.js version

20.17.0

### java version

17.0.12

### Application/Library version

5.0.0-beta

### Error logs or screenshots

```
/home/bot-core/node_modules/zod/lib/types.js:160
        throw result.error;
        ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "undefined",
    "path": [
      "NODES"
    ],
    "message": "Required"
  }
]
    at get error [as error] (/home/bot-core/node_modules/zod/lib/types.js:55:31)
    at ZodObject.parse (/home/bot-core/node_modules/zod/lib/types.js:160:22)
    at Object.<anonymous> (/home/bot-core/dist/env.js:118:25)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/bot-core/dist/shard.js:5:15) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'undefined',
      path: [ 'NODES' ],
      message: 'Required'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'array',
      received: 'undefined',
      path: [ 'NODES' ],
      message: 'Required'
    }
  ]
}
```

### Additional context

[.env.txt](https://github.com/user-attachments/files/17171727/default.env.txt)

**Comment by appujet** [comment]
Please add .env file

**Comment by cristofer96** [comment]
Same error here!

**Comment by cristofer96** [comment]
NODES=[{"id":"node1","host":"localhost","port":8080,"authorization":"your_auth_key"}]

Solved  introducing this to .env

**Comment by SsSAtonioSsS** [comment]
The .env file was added in the Additional context block. I am duplicating the link to it.
https://github.com/user-attachments/files/17171727/default.env.txt

**Comment by infnibor** [comment]
> The .env file was added in the Additional context block. I am duplicating the link to it. https://github.com/user-attachments/files/17171727/default.env.txt

You must have downloaded some old env, or deleted something by accident, in env.example there is a line about lavalink calls, so be on your side 
![image](https://github.com/user-attachments/assets/5ddafd5c-db3b-4cd5-867e-e2a25ef01195)
https://github.com/appujet/lavamusic/blob/main/.env.example

**Comment by SsSAtonioSsS** [comment]
Oh, yeah. Downloaded the template from the old version from https://appujet.github.io/lavamusic/.
