### ISSUE TITLE
[Bug]: Slash command not loading

### ISSUE THREAD

**Issue by nxxju** [appujet/lavamusic#754]
### Bug description

Slash commands are not loading in the bot and henceforth no slash command are accessible

### Steps to reproduce

Fix slash command

### Operating System

Windows 11

### Node.js version

21

### java version

17

### Application/Library version

5.0.0-beta

### Error logs or screenshots

There are no logs

**Comment by CharlesNaig** [comment]
have you used the deploy command?

**Comment by CharlesNaig** [comment]
https://github.com/appujet/lavamusic/blob/main/src/commands/dev/Deploy.ts

**Comment by hwangsihu** [comment]
I think we need an automatic deployment feature. Many people, including myself, often forget the deployment command.
